/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CapsulMeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "balanceOf"
      | "capsules"
      | "getApproved"
      | "getPactInvites"
      | "getPactSigners"
      | "getReceivedCapsules"
      | "getSentCapsules"
      | "ipfsGateway"
      | "isApprovedForAll"
      | "mintPactCapsule"
      | "mintSelfCapsule"
      | "mintSendCapsule"
      | "name"
      | "openCapsule"
      | "owner"
      | "ownerOf"
      | "pactSigned"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setImageCIDs"
      | "setIpfsGateway"
      | "signPact"
      | "supportsInterface"
      | "symbol"
      | "tierImageCIDs"
      | "timeRemaining"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "CapsuleMinted"
      | "CapsuleOpened"
      | "ImageCIDsUpdated"
      | "OwnershipTransferred"
      | "PactMinted"
      | "PactSigned"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "capsules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPactInvites",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPactSigners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceivedCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSentCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ipfsGateway",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintPactCapsule",
    values: [string, AddressLike[], BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSelfCapsule",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSendCapsule",
    values: [string, BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openCapsule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pactSigned",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setImageCIDs",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setIpfsGateway",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "signPact",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tierImageCIDs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "capsules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPactInvites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPactSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceivedCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSentCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ipfsGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintPactCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintSelfCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintSendCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pactSigned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImageCIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIpfsGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signPact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tierImageCIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsuleMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    sender: AddressLike,
    receiver: AddressLike,
    unlockTime: BigNumberish,
    tier: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    sender: string,
    receiver: string,
    unlockTime: bigint,
    tier: bigint,
    value: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    sender: string;
    receiver: string;
    unlockTime: bigint;
    tier: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsuleOpenedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    opener: AddressLike,
    claimedValue: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    opener: string,
    claimedValue: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    opener: string;
    claimedValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImageCIDsUpdatedEvent {
  export type InputTuple = [pinkCID: string, redCID: string, blackCID: string];
  export type OutputTuple = [pinkCID: string, redCID: string, blackCID: string];
  export interface OutputObject {
    pinkCID: string;
    redCID: string;
    blackCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    initiator: AddressLike,
    signers: AddressLike[],
    threshold: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    initiator: string,
    signers: string[],
    threshold: bigint,
    value: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    initiator: string;
    signers: string[];
    threshold: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactSignedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    signer: AddressLike,
    signCount: BigNumberish,
    threshold: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    signer: string,
    signCount: bigint,
    threshold: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    signer: string;
    signCount: bigint;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CapsulMe extends BaseContract {
  connect(runner?: ContractRunner | null): CapsulMe;
  waitForDeployment(): Promise<this>;

  interface: CapsulMeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  capsules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        encryptedCID: string;
        unlockTime: bigint;
        sender: string;
        receiver: string;
        tier: bigint;
        status: bigint;
        title: string;
        lockedValue: bigint;
        capsuleType: bigint;
        pactThreshold: bigint;
        pactSignCount: bigint;
      }
    ],
    "view"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getPactInvites: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  getPactSigners: TypedContractMethod<
    [_tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  getReceivedCapsules: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getSentCapsules: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  ipfsGateway: TypedContractMethod<[], [string], "view">;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintPactCapsule: TypedContractMethod<
    [
      _encryptedCID: string,
      _signers: AddressLike[],
      _threshold: BigNumberish,
      _title: string
    ],
    [bigint],
    "payable"
  >;

  mintSelfCapsule: TypedContractMethod<
    [_encryptedCID: string, _unlockTime: BigNumberish, _title: string],
    [bigint],
    "payable"
  >;

  mintSendCapsule: TypedContractMethod<
    [
      _encryptedCID: string,
      _unlockTime: BigNumberish,
      _receiver: AddressLike,
      _title: string
    ],
    [bigint],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  openCapsule: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  pactSigned: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setImageCIDs: TypedContractMethod<
    [_pinkCID: string, _redCID: string, _blackCID: string],
    [void],
    "nonpayable"
  >;

  setIpfsGateway: TypedContractMethod<[_gateway: string], [void], "nonpayable">;

  signPact: TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tierImageCIDs: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  timeRemaining: TypedContractMethod<
    [_tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "capsules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        encryptedCID: string;
        unlockTime: bigint;
        sender: string;
        receiver: string;
        tier: bigint;
        status: bigint;
        title: string;
        lockedValue: bigint;
        capsuleType: bigint;
        pactThreshold: bigint;
        pactSignCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPactInvites"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPactSigners"
  ): TypedContractMethod<[_tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReceivedCapsules"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSentCapsules"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "ipfsGateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintPactCapsule"
  ): TypedContractMethod<
    [
      _encryptedCID: string,
      _signers: AddressLike[],
      _threshold: BigNumberish,
      _title: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintSelfCapsule"
  ): TypedContractMethod<
    [_encryptedCID: string, _unlockTime: BigNumberish, _title: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintSendCapsule"
  ): TypedContractMethod<
    [
      _encryptedCID: string,
      _unlockTime: BigNumberish,
      _receiver: AddressLike,
      _title: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openCapsule"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pactSigned"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setImageCIDs"
  ): TypedContractMethod<
    [_pinkCID: string, _redCID: string, _blackCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIpfsGateway"
  ): TypedContractMethod<[_gateway: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signPact"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tierImageCIDs"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "timeRemaining"
  ): TypedContractMethod<[_tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "CapsuleMinted"
  ): TypedContractEvent<
    CapsuleMintedEvent.InputTuple,
    CapsuleMintedEvent.OutputTuple,
    CapsuleMintedEvent.OutputObject
  >;
  getEvent(
    key: "CapsuleOpened"
  ): TypedContractEvent<
    CapsuleOpenedEvent.InputTuple,
    CapsuleOpenedEvent.OutputTuple,
    CapsuleOpenedEvent.OutputObject
  >;
  getEvent(
    key: "ImageCIDsUpdated"
  ): TypedContractEvent<
    ImageCIDsUpdatedEvent.InputTuple,
    ImageCIDsUpdatedEvent.OutputTuple,
    ImageCIDsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PactMinted"
  ): TypedContractEvent<
    PactMintedEvent.InputTuple,
    PactMintedEvent.OutputTuple,
    PactMintedEvent.OutputObject
  >;
  getEvent(
    key: "PactSigned"
  ): TypedContractEvent<
    PactSignedEvent.InputTuple,
    PactSignedEvent.OutputTuple,
    PactSignedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "CapsuleMinted(uint256,address,address,uint256,uint8,uint256)": TypedContractEvent<
      CapsuleMintedEvent.InputTuple,
      CapsuleMintedEvent.OutputTuple,
      CapsuleMintedEvent.OutputObject
    >;
    CapsuleMinted: TypedContractEvent<
      CapsuleMintedEvent.InputTuple,
      CapsuleMintedEvent.OutputTuple,
      CapsuleMintedEvent.OutputObject
    >;

    "CapsuleOpened(uint256,address,uint256)": TypedContractEvent<
      CapsuleOpenedEvent.InputTuple,
      CapsuleOpenedEvent.OutputTuple,
      CapsuleOpenedEvent.OutputObject
    >;
    CapsuleOpened: TypedContractEvent<
      CapsuleOpenedEvent.InputTuple,
      CapsuleOpenedEvent.OutputTuple,
      CapsuleOpenedEvent.OutputObject
    >;

    "ImageCIDsUpdated(string,string,string)": TypedContractEvent<
      ImageCIDsUpdatedEvent.InputTuple,
      ImageCIDsUpdatedEvent.OutputTuple,
      ImageCIDsUpdatedEvent.OutputObject
    >;
    ImageCIDsUpdated: TypedContractEvent<
      ImageCIDsUpdatedEvent.InputTuple,
      ImageCIDsUpdatedEvent.OutputTuple,
      ImageCIDsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PactMinted(uint256,address,address[],uint256,uint256)": TypedContractEvent<
      PactMintedEvent.InputTuple,
      PactMintedEvent.OutputTuple,
      PactMintedEvent.OutputObject
    >;
    PactMinted: TypedContractEvent<
      PactMintedEvent.InputTuple,
      PactMintedEvent.OutputTuple,
      PactMintedEvent.OutputObject
    >;

    "PactSigned(uint256,address,uint256,uint256)": TypedContractEvent<
      PactSignedEvent.InputTuple,
      PactSignedEvent.OutputTuple,
      PactSignedEvent.OutputObject
    >;
    PactSigned: TypedContractEvent<
      PactSignedEvent.InputTuple,
      PactSignedEvent.OutputTuple,
      PactSignedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
